from __future__ import annotations

import asyncio
import json
import os
import random
import time
import uuid
from datetime import datetime, timezone
from typing import Literal

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from prometheus_client import Counter, Gauge, Histogram, make_asgi_app

NODE_ID = os.getenv("NODE_ID", "payment-node-unknown")
SERVICE_VERSION = os.getenv("SERVICE_VERSION", "0.6.0")
STARTED_AT_MONOTONIC = time.monotonic()
restart_generation = 0
last_restart_at: str | None = None
last_restart_reason = "startup"

FaultMode = Literal["none", "unavailable", "shared_dependency", "timeout", "hung"]

PAYMENT_REQUESTS = Counter(
    "opsai_payment_requests_total",
    "Payment requests processed by a node.",
    ["node", "status"],
)
PAYMENT_DURATION = Histogram(
    "opsai_payment_processing_duration_seconds",
    "Payment processing time inside the selected node.",
    ["node"],
    # Extra sub-second buckets make bounded scale-up recovery independently
    # verifiable instead of relying on traffic expiry or router-window decay.
    buckets=(0.025, 0.05, 0.075, 0.1, 0.15, 0.25, 0.5, 0.6, 0.7, 0.8, 1, 2, 5),
)
INJECTED_FAILURES = Counter(
    "opsai_payment_injected_failures_total",
    "Failures generated by a controlled scenario.",
    ["node", "mode"],
)
FAULT_MODE_INFO = Gauge(
    "opsai_payment_fault_mode_info",
    "One for the active controlled fault mode and zero otherwise.",
    ["node", "mode"],
)
CAPACITY_UNITS = Gauge(
    "opsai_payment_capacity_units",
    "Bounded simulated processing-capacity units configured for a payment node.",
    ["node"],
)
CAPACITY_PRESSURE = Gauge(
    "opsai_payment_capacity_pressure_milliseconds",
    "Controlled per-request capacity-pressure delay before capacity scaling.",
    ["node"],
)

SERVICE_RESTARTS = Counter(
    "opsai_payment_service_restarts_total",
    "Bounded application-level restart simulations executed for a payment node.",
    ["node", "reason"],
)
RESTART_GENERATION = Gauge(
    "opsai_payment_restart_generation",
    "Monotonic bounded application restart generation.",
    ["node"],
)

app = FastAPI(title="PulseGuard Payment Service", version=SERVICE_VERSION)
app.mount("/metrics", make_asgi_app())
current_fault_mode: FaultMode = "none"
all_fault_modes: tuple[FaultMode, ...] = ("none", "unavailable", "shared_dependency", "timeout", "hung")
last_fault_changed_at: str | None = None
current_capacity_units = 1
capacity_pressure_ms = 0
last_capacity_changed_at: str | None = None
last_capacity_change_reason = "startup"
MAX_CAPACITY_UNITS = 3


class PaymentRequest(BaseModel):
    orderId: str = Field(min_length=1, max_length=100)
    amount: float = Field(gt=0)
    currency: str = Field(default="USD", min_length=3, max_length=3)


class PaymentResponse(BaseModel):
    status: str
    transactionId: str
    orderId: str
    processedBy: str
    processingTimeMs: int
    version: str


class FaultRequest(BaseModel):
    mode: FaultMode


class CapacityRequest(BaseModel):
    units: int = Field(default=1, ge=1, le=MAX_CAPACITY_UNITS)
    pressureMs: int = Field(default=0, ge=0, le=2500)
    reason: str = Field(default="manual", min_length=2, max_length=80)


class RestartRequest(BaseModel):
    reason: str = Field(default="operator_approved_restart", min_length=2, max_length=100)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def emit_log(level: str, event: str, **fields: object) -> None:
    print(
        json.dumps(
            {
                "timestamp": utc_now(),
                "level": level,
                "service": "payment-service",
                "nodeId": NODE_ID,
                "version": SERVICE_VERSION,
                "event": event,
                **fields,
            },
            separators=(",", ":"),
        ),
        flush=True,
    )


def set_fault_metrics(mode: FaultMode) -> None:
    for item in all_fault_modes:
        FAULT_MODE_INFO.labels(node=NODE_ID, mode=item).set(1 if item == mode else 0)


def set_capacity_metrics() -> None:
    CAPACITY_UNITS.labels(node=NODE_ID).set(current_capacity_units)
    CAPACITY_PRESSURE.labels(node=NODE_ID).set(capacity_pressure_ms)


def apply_capacity(
    units: int,
    pressure_ms: int | None = None,
    reason: str = "manual",
) -> None:
    global current_capacity_units, capacity_pressure_ms
    global last_capacity_changed_at, last_capacity_change_reason
    previous_units = current_capacity_units
    previous_pressure_ms = capacity_pressure_ms
    current_capacity_units = max(1, min(MAX_CAPACITY_UNITS, int(units)))
    if pressure_ms is not None:
        capacity_pressure_ms = max(0, min(2500, int(pressure_ms)))
    last_capacity_changed_at = utc_now()
    last_capacity_change_reason = reason
    set_capacity_metrics()
    emit_log(
        "INFO",
        "capacity_profile_changed",
        previousCapacityUnits=previous_units,
        capacityUnits=current_capacity_units,
        previousCapacityPressureMs=previous_pressure_ms,
        capacityPressureMs=capacity_pressure_ms,
        capacityChangeReason=reason,
        simulated=True,
    )


def apply_fault_mode(mode: FaultMode) -> None:
    global current_fault_mode, last_fault_changed_at
    current_fault_mode = mode
    last_fault_changed_at = utc_now()
    set_fault_metrics(mode)
    emit_log(
        "WARNING" if mode != "none" else "INFO",
        "controlled_fault_changed",
        faultMode=mode,
    )


def perform_bounded_restart(reason: str) -> dict[str, object]:
    """Reset application worker state without Docker/socket or host-level access."""
    global STARTED_AT_MONOTONIC, restart_generation, last_restart_at, last_restart_reason
    previous_fault = current_fault_mode
    apply_fault_mode("none")
    STARTED_AT_MONOTONIC = time.monotonic()
    restart_generation += 1
    last_restart_at = utc_now()
    last_restart_reason = reason
    SERVICE_RESTARTS.labels(node=NODE_ID, reason=reason).inc()
    RESTART_GENERATION.labels(node=NODE_ID).set(restart_generation)
    emit_log(
        "WARNING",
        "bounded_application_restart_completed",
        reason=reason,
        previousFaultMode=previous_fault,
        restartGeneration=restart_generation,
        dockerRestart=False,
        processReplacement=False,
    )
    return {
        "nodeId": NODE_ID,
        "previousFaultMode": previous_fault,
        "faultMode": current_fault_mode,
        "restartGeneration": restart_generation,
        "restartedAt": last_restart_at,
        "reason": reason,
        "boundedApplicationRestart": True,
        "dockerRestart": False,
        "hostMutation": False,
    }


@app.on_event("startup")
async def startup_event() -> None:
    set_fault_metrics(current_fault_mode)
    set_capacity_metrics()
    RESTART_GENERATION.labels(node=NODE_ID).set(restart_generation)
    emit_log("INFO", "service_started", capacityUnits=current_capacity_units)


@app.get("/")
async def root() -> dict[str, object]:
    return {
        "service": "payment-service",
        "nodeId": NODE_ID,
        "version": SERVICE_VERSION,
        "faultMode": current_fault_mode,
    }


@app.get("/health")
async def health() -> dict[str, object]:
    # The process remains healthy so Docker does not restart it during a deliberate demo fault.
    return {
        "status": "healthy",
        "service": "payment-service",
        "nodeId": NODE_ID,
        "version": SERVICE_VERSION,
        "acceptingPayments": current_fault_mode == "none",
        "faultMode": current_fault_mode,
        "capacityUnits": current_capacity_units,
        "capacityPressureMs": capacity_pressure_ms,
        "capacityChangedAt": last_capacity_changed_at,
        "capacityChangeReason": last_capacity_change_reason,
        "capacitySimulation": True,
        "restartGeneration": restart_generation,
        "lastRestartAt": last_restart_at,
        "lastRestartReason": last_restart_reason,
    }


@app.get("/admin/diagnostics")
async def diagnostics() -> dict[str, object]:
    return {
        "nodeId": NODE_ID,
        "serviceVersion": SERVICE_VERSION,
        "processStatus": "running",
        "acceptingPayments": current_fault_mode == "none",
        "faultMode": current_fault_mode,
        "faultChangedAt": last_fault_changed_at,
        "capacityUnits": current_capacity_units,
        "capacityPressureMs": capacity_pressure_ms,
        "capacityChangedAt": last_capacity_changed_at,
        "capacityChangeReason": last_capacity_change_reason,
        "capacitySimulation": True,
        "restartGeneration": restart_generation,
        "lastRestartAt": last_restart_at,
        "lastRestartReason": last_restart_reason,
        "uptimeSeconds": round(time.monotonic() - STARTED_AT_MONOTONIC, 2),
    }


@app.post("/admin/fault")
async def set_fault(request: FaultRequest) -> dict[str, object]:
    apply_fault_mode(request.mode)
    return await diagnostics()


@app.post("/admin/fault/reset")
async def reset_fault() -> dict[str, object]:
    apply_fault_mode("none")
    return await diagnostics()


@app.post("/admin/restart")
async def restart_service(request: RestartRequest) -> dict[str, object]:
    result = perform_bounded_restart(request.reason)
    result["diagnostics"] = await diagnostics()
    return result


@app.post("/admin/capacity")
async def set_capacity(request: CapacityRequest) -> dict[str, object]:
    apply_capacity(request.units, request.pressureMs, request.reason)
    return await diagnostics()


@app.post("/admin/capacity/reset")
async def reset_capacity() -> dict[str, object]:
    apply_capacity(1, 0, "scenario_reset")
    return await diagnostics()


@app.post("/payments", response_model=PaymentResponse)
async def process_payment(request: PaymentRequest) -> PaymentResponse:
    mode = current_fault_mode
    if mode == "unavailable":
        PAYMENT_REQUESTS.labels(node=NODE_ID, status="unavailable").inc()
        INJECTED_FAILURES.labels(node=NODE_ID, mode=mode).inc()
        emit_log(
            "ERROR",
            "payment_rejected_by_controlled_fault",
            orderId=request.orderId,
            faultMode=mode,
        )
        raise HTTPException(
            status_code=503,
            detail=f"{NODE_ID} is unavailable because a controlled scenario is active.",
        )

    if mode == "shared_dependency":
        PAYMENT_REQUESTS.labels(node=NODE_ID, status="dependency_failed").inc()
        INJECTED_FAILURES.labels(node=NODE_ID, mode=mode).inc()
        emit_log(
            "ERROR",
            "shared_dependency_unavailable",
            orderId=request.orderId,
            dependency="payment-authorisation-provider",
        )
        raise HTTPException(
            status_code=503,
            detail="Shared payment-authorisation dependency is unavailable.",
        )

    if mode == "hung":
        PAYMENT_REQUESTS.labels(node=NODE_ID, status="hung").inc()
        INJECTED_FAILURES.labels(node=NODE_ID, mode=mode).inc()
        emit_log(
            "ERROR",
            "payment_worker_hung",
            orderId=request.orderId,
            delaySeconds=30,
            restartGeneration=restart_generation,
        )
        await asyncio.sleep(30)

    if mode == "timeout":
        PAYMENT_REQUESTS.labels(node=NODE_ID, status="timeout").inc()
        INJECTED_FAILURES.labels(node=NODE_ID, mode=mode).inc()
        emit_log(
            "ERROR",
            "payment_timeout_controlled_fault",
            orderId=request.orderId,
            delaySeconds=8,
        )
        await asyncio.sleep(8)

    started = time.perf_counter()
    baseline_delay_ms = random.randint(45, 140)
    scaled_pressure_ms = round(capacity_pressure_ms / max(1, current_capacity_units))
    processing_delay_ms = baseline_delay_ms + scaled_pressure_ms
    await asyncio.sleep(processing_delay_ms / 1000)
    elapsed_seconds = time.perf_counter() - started
    elapsed_ms = round(elapsed_seconds * 1000)
    transaction_id = f"TXN-{uuid.uuid4().hex[:12].upper()}"

    PAYMENT_REQUESTS.labels(node=NODE_ID, status="approved").inc()
    PAYMENT_DURATION.labels(node=NODE_ID).observe(elapsed_seconds)

    emit_log(
        "INFO",
        "payment_processed",
        orderId=request.orderId,
        amount=round(request.amount, 2),
        currency=request.currency,
        durationMs=elapsed_ms,
        status="approved",
        transactionId=transaction_id,
        capacityUnits=current_capacity_units,
        capacityPressureMs=capacity_pressure_ms,
        simulatedCapacity=True,
    )

    return PaymentResponse(
        status="approved",
        transactionId=transaction_id,
        orderId=request.orderId,
        processedBy=NODE_ID,
        processingTimeMs=elapsed_ms,
        version=SERVICE_VERSION,
    )
